### ISSUE TITLE
Initial Barnacle release

### ISSUE THREAD

**Issue by tanaes** [biocore/oecophylla#101]
We're close to being ready to release this to Barnacle! The launch script now makes it very easy to launch a run on either the included test data sets or your own (PR #98). 

A few remaining issues to close:

- [ ] Make sure we have included outputs that are compatible with some form of UniFrac #94 #93 #8
- [x] Update documentation to do a walk-through execution with test data, and with own data #58
- [x] Include Barnacle parameters file with database paths #59 
- [x] Make sure we have SHOGUN shallow functional prediction rule #20 

Thanks so much for all your help making this happen!
